### ISSUE TITLE
ace wikipedia:  Error: Could not parse out canonical url for undefined

### ISSUE THREAD

**Issue by lidel** [ipfs/distributed-wikipedia-mirror#81]
Seems that some languages are failing due to missing canonical link?

```console
$ ./mirrorzim.sh --languagecode=ace --wikitype=wikipedia
[...]
Unpack the zim file into ./tmp/wikipedia_ace_all_maxi_2021-02...

Convert the unpacked zim directory to a website
-------------------------
Zim to Website Conversion
-------------------------
  Unpacked Zim Directory: ./tmp/wikipedia_ace_all_maxi_2021-02
                Zim File: ./snapshots/wikipedia_ace_all_maxi_2021-02.zim
               Main Page: %C3%94n_Keue
         Kiwix Main Page: Ôn_Keue
-------------------------

Starting zim to website conversion ...
  Copying source ZIM to the root of unpacked zim directory ... done
  Copying image assets into unpacked zim directory ... done
  Fixing favicon ... done
  Renaming A namespace to wiki ... done
  Fixing redirects ... done
  Inserting root 'index.html' as redirect to main page... done
  Appending custom javascript to site.js ... done
  Generating main page into tmp/wikipedia_ace_all_maxi_2021-02/wiki/index.html ... !
Error: Could not parse out canonical url for undefined
    at Object.exports.generateMainPage (/media/distributed-wikipedia-mirror/src/site-transforms.ts:192:11)
    at Object.exports.zimToWebsite (/media/distributed-wikipedia-mirror/src/zim-to-website.ts:54:9)
    at ZimToWebsite.run (/media/distributed-wikipedia-mirror/src/index.ts:65:5)
    at ZimToWebsite._run (/media/distributed-wikipedia-mirror/node_modules/@oclif/command/lib/command.js:44:20)

**Comment by lidel** [comment]
No longer an issue with latest scripts and `wikipedia_ace_all_maxi_2021-03.zim`
